name: EssentialsPE
main: EssentialsPE\Loader
version: 2.1.0
api: [3.2.5]
author: LegendsOfMCPE Team
authors: ProxyTechDevs

permissions:
    essentials:
        default: false
        description: ""
        children:
            essentials.ban:
                default: false
                description: ""
                children:
                    essentials.ban.exempt:
                        default: false
                        description: ""
            essentials.colorchat:
                default: false
                description: ""
            essentials.afk:
                default: false
                description: ""
                children:
                    essentials.afk.use:
                        default: false
                        description: ""
                    essentials.afk.other:
                        default: false
                        description: ""
                    essentials.afk.preventauto:
                        default: false
                        description: ""
                    essentials.afk.kickexempt:
                        default: false
                        description: ""
            essentials.antioch:
                default: false
                description: ""
            essentials.back:
                default: false
                description: ""
                children:
                    essentials.back.use:
                        default: false
                        description: ""
            essentials.bigtree:
                default: false
                description: ""
            essentials.break:
                default: false
                description: ""
                children:
                    essentials.break.use:
                        default: false
                        description: ""
                    essentials.break.bedrock:
                        default: false
                        description: ""
            essentials.broadcast:
                default: false
                description: ""
            essentials.burn:
                default: false
                description: ""
            essentials.clearinventory:
                default: false
                description: ""
                children:
                    essentials.clearinventory.use:
                        default: false
                        description: ""
                    essentials.clearinventory.other:
                        default: false
                        description: ""
            essentials.compass:
                default: false
                description: ""
            essentials.condense:
                default: false
                description: ""
            essentials.delhome:
                default: false
                description: ""
            essentials.delwarp:
                default: false
                description: ""
            essentials.depth:
                default: false
                description: ""
            essentials.essentials:
                default: false
                description: ""
            essentials.extinguish:
                default: false
                description: ""
                children:
                    essentials.extinguish.use:
                        default: false
                        description: ""
                    essentials.extinguish.other:
                        default: false
                        description: ""
            essentials.fly:
                default: false
                description: ""
                children:
                    essentials.fly.use:
                        default: false
                        description: ""
                    essentials.fly.others:
                        default: false
                        description: ""
            essentials.feed:
                default: false
                description: ""
                children:
                    essentials.feed.use:
                        default: false
                        description: ""
                    essentials.feed.other:
                        default: false
                        description: ""
            essentials.gamemode:
                default: false
                description: ""
                children:
                    essentials.gamemode.use:
                        default: false
                        description: ""
                    essentials.gamemode.other:
                        default: false
                        description: ""
            essentials.geoip:
                default: false
                description: ""
                children:
                    essentials.geoip.show:
                        default: false
                        description: ""
                    essentials.geoip.hide:
                        default: false
                        description: ""
            essentials.getpos:
                default: false
                description: ""
                children:
                    essentials.getpos.use:
                        default: false
                        description: ""
                    essentials.getpos.other:
                        default: false
                        description: ""
            essentials.god:
                default: false
                description: ""
                children:
                    essentials.god.use:
                        default: false
                        description: ""
                    essentials.god.other:
                        default: false
                        description: ""
                    essentials.god.pvp:
                        default: false
                        description: ""
            essentials.hat:
                default: false
                description: ""
            essentials.heal:
                default: false
                description: ""
                children:
                    essentials.heal.use:
                        default: false
                        description: ""
                    essentials.heal.other:
                        default: false
                        description: ""
            essentials.home:
                default: false
                description: ""
                children:
                    essentials.home.use:
                        default: false
                        description: ""
                    essentials.home.bed:
                        default: false
                        description: ""
            essentials.item:
                default: false
                description: ""
            essentials.itemdb:
                default: false
                description: ""
            essentials.itemspawn:
                default: false
                description: ""
                children:
                    essentials.itemspawn.item-all:
                        default: false
                        description: ""
                    #essentials.itemspawn.exempt:
                    #    default: false
                    #    description: ""
            essentials.jump:
                default: false
                description: ""
            essentials.kickall:
                default: false
                description: ""
            essentials.kill:
                default: false
                description: ""
                children:
                    essentials.kill.use:
                        default: false
                        description: ""
                    essentials.kill.other:
                        default: false
                        description: ""
            essentials.lightning:
                default: false
                description: ""
            essentials.more:
                default: false
                description: ""
            essentials.msg:
                default: false
                description: ""
            essentials.mute:
                default: false
                description: ""
                children:
                    essentials.mute.use:
                        default: false
                        description: ""
                    essentials.mute.exempt:
                        default: false
                        description: ""
                    essentials.mute.notify:
                        default: false
                        description: ""
            essentials.near:
                default: false
                description: ""
                children:
                    essentials.near.use:
                        default: false
                        description: ""
                    essentials.near.other:
                        default: false
                        description: ""
            essentials.nick:
                default: false
                description: ""
                children:
                    essentials.nick.use:
                        default: false
                        description: ""
                    essentials.nick.other:
                        default: false
                        description: ""
            essentials.nuke:
                default: false
                description: ""
                children:
                    essentials.nuke.use:
                        default: false
                        description: ""
                    essentials.nuke.other:
                        default: false
                        description: ""
            essentials.oversizedstacks:
                default: false
                description: ""
            essentials.powertool:
                default: false
                description: ""
                children:
                    essentials.powertool.use:
                        default: false
                        description: ""
                    essentials.powertool.append:
                        default: false
                        description: ""
            essentials.powertooltoggle:
                default: false
                description: ""
            essentials.ptime:
               default: false
               description: ""
               children:
                    essentials.ptime.use:
                        default: false
                        description: ""
                    essentials.ptime.other:
                        default: false
                        description: ""
            essentials.pvp:
                default: false
                description: ""
            essentials.realname:
                default: false
                description: ""
            essentials.repair:
                default: false
                description: ""
                children:
                    essentials.repair.use:
                        default: false
                        description: ""
                    essentials.repair.all:
                        default: false
                        description: ""
                    essentials.repair.armor:
                        default: false
                        description: ""
            essentials.reply:
                default: false
                description: ""
            essentials.seen:
                default: false
                description: ""
            essentials.sethome:
                default: false
                description: ""
            essentials.setspawn:
                default: false
                description: ""
            essentials.setwarp:
                default: false
                description: ""
            essentials.sign:
                default: false
                description: ""
                children:
                    essentials.sign.break:
                        default: false
                        description: ""
                        children:
                            essentials.sign.break.free:
                                default: false
                                description: ""
                            essentials.sign.break.gamemode:
                                default: false
                                description: ""
                            essentials.sign.break.heal:
                                default: false
                                description: ""
                            essentials.sign.break.repair:
                                default: false
                                description: ""
                            essentials.sign.break.time:
                                default: false
                                description: ""
                            essentials.sign.break.teleport:
                                default: false
                                description: ""
                            essentials.sign.break.warp:
                                default: false
                                description: ""
                    essentials.sign.color:
                        default: false
                        description: ""
                    essentials.sign.create:
                        default: false
                        description: ""
                        children:
                            essentials.sign.create.free:
                                default: false
                                description: ""
                            essentials.sign.create.gamemode:
                                default: false
                                description: ""
                            essentials.sign.create.heal:
                                default: false
                                description: ""
                            essentials.sign.create.repair:
                                default: false
                                description: ""
                            essentials.sign.create.time:
                                default: false
                                description: ""
                            essentials.sign.create.teleport:
                                default: false
                                description: ""
                            essentials.sign.create.warp:
                                default: false
                                description: ""
                    essentials.sign.nopay:
                        default: false
                        description: ""
                    essentials.sign.use:
                        default: false
                        description: ""
                        children:
                            essentials.sign.use.free:
                                default: false
                                description: ""
                            essentials.sign.use.gamemode:
                                default: false
                                description: ""
                            essentials.sign.use.heal:
                                default: false
                                description: ""
                            essentials.sign.use.repair:
                                default: false
                                description: ""
                            essentials.sign.use.time:
                                default: false
                                description: ""
                            essentials.sign.use.teleport:
                                default: false
                                description: ""
                            essentials.sign.use.warp:
                                default: false
                                description: ""
            essentials.spawn:
                default: false
                description: ""
                children:
                    essentials.spawn.use:
                        default: false
                        description: ""
                    essentials.spawn.other:
                        default: false
                        description: ""
            essentials.sudo:
                default: false
                description: ""
                children:
                    essentials.sudo.use:
                        default: false
                        description: ""
                    essentials.sudo.exempt:
                        default: false
                        description: ""
            essentials.suicide:
                default: false
                description: ""
            essentials.tpa:
                default: false
                description: ""
            essentials.tpaccept:
                default: false
                description: ""
            essentials.tpahere:
                default: false
                description: ""
            essentials.tpall:
                default: false
                description: ""
            essentials.tpdeny:
                default: false
                description: ""
            essentials.tphere:
                default: false
                description: ""
            essentials.tempban:
                default: false
                description: ""
            essentials.top:
                default: false
                description: ""
            essentials.tree:
                default: false
                description: ""
            essentials.unlimited:
                default: false
                description: ""
                children:
                    essentials.unlimited.use:
                        default: false
                        description: ""
                    essentials.unlimited.other:
                        default: false
                        description: ""
            essentials.vanish:
                default: false
                description: ""
                children:
                    essentials.vanish.use:
                        default: false
                        description: ""
                    essentials.vanish.other:
                        default: false
                        description: ""
                    essentials.vanish.pvp:
                        default: false
                        description: ""
            essentials.warp:
                default: false
                description: ""
                children:
                    essentials.warp.use:
                        default: false
                        description: ""
                    essentials.warp.other:
                        default: false
                        description: ""
            essentials.whois:
                default: false
                description: ""
            essentials.world:
                default: false
                description: ""
