version: "0.0.4"
homes: true
warps: true
powertool: true
teleporting: true
afk:
  safe: false
  auto-set: 0
  auto-broadcast: false
  auto-kick: 0
  broadcast: false
oversized-stacks: 64
near-radius-limit: 10
near-default-radius: 10
enable-custom-colors: false
